use std::io;
use std::path::Path;

use crate::error::ClawError;

/// Collected answers from the interactive init prompts.
pub struct InitAnswers {
    pub anthropic_api_key: Option<String>,
    pub openai_api_key: Option<String>,
}

/// Abstraction over I/O for testability.
pub trait InitPrompter {
    fn println(&mut self, msg: &str);
    fn read_password(&mut self, prompt: &str) -> io::Result<String>;
    fn confirm(&mut self, prompt: &str) -> io::Result<bool>;
}

/// Real prompter using stdin + rpassword.
pub struct StdioPrompter;

impl InitPrompter for StdioPrompter {
    fn println(&mut self, msg: &str) {
        println!("{msg}");
    }

    fn read_password(&mut self, prompt: &str) -> io::Result<String> {
        rpassword::prompt_password(prompt)
    }

    fn confirm(&mut self, prompt: &str) -> io::Result<bool> {
        use std::io::Write;
        print!("{prompt}");
        io::stdout().flush()?;
        let mut input = String::new();
        io::stdin().read_line(&mut input)?;
        let trimmed = input.trim().to_lowercase();
        Ok(trimmed.is_empty() || trimmed == "y" || trimmed == "yes")
    }
}

/// Generate TOML config string from init answers (pure function).
pub fn generate_config_toml(answers: &InitAnswers) -> String {
    let mut out = String::from(
        "# clawzero configuration\n\
         # Generated by `clawzero init`\n\
         \n\
         [defaults]\n\
         model = \"anthropic/claude-sonnet-4-20250514\"\n\
         max_tokens = 8192\n",
    );

    if let Some(ref key) = answers.anthropic_api_key {
        out.push_str(&format!(
            "\n[providers.anthropic]\n\
             protocol = \"anthropic\"\n\
             base_url = \"https://api.anthropic.com\"\n\
             api_key = \"{key}\"\n"
        ));
    }

    if let Some(ref key) = answers.openai_api_key {
        out.push_str(&format!(
            "\n[providers.openai]\n\
             protocol = \"openai\"\n\
             base_url = \"https://api.openai.com\"\n\
             api_key = \"{key}\"\n"
        ));
    }

    out
}

/// Write config string to file, creating parent directories and setting 0600 permissions.
pub fn write_config(path: &Path, content: &str) -> Result<(), ClawError> {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, content)?;

    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let perms = std::fs::Permissions::from_mode(0o600);
        std::fs::set_permissions(path, perms)?;
    }

    Ok(())
}

/// Run the interactive init flow.
pub fn run_init(prompter: &mut dyn InitPrompter, config_path: &Path) -> Result<(), ClawError> {
    prompter.println("Welcome to clawzero setup!");
    prompter.println("");

    // Check for existing config
    if config_path.exists() {
        let overwrite = prompter
            .confirm("Config file already exists. Overwrite? [Y/n] ")
            .map_err(|e| ClawError::Config(format!("Failed to read input: {e}")))?;
        if !overwrite {
            prompter.println("Aborted. Existing config unchanged.");
            return Ok(());
        }
    }

    // Anthropic API key
    let anthropic_key = prompter
        .read_password("Enter your Anthropic API key (leave empty to skip): ")
        .map_err(|e| ClawError::Config(format!("Failed to read API key: {e}")))?;
    let anthropic_api_key = if anthropic_key.trim().is_empty() {
        None
    } else {
        Some(anthropic_key.trim().to_string())
    };

    // OpenAI API key
    let openai_api_key = if prompter
        .confirm("Also configure OpenAI? [Y/n] ")
        .map_err(|e| ClawError::Config(format!("Failed to read input: {e}")))?
    {
        let key = prompter
            .read_password("Enter your OpenAI API key: ")
            .map_err(|e| ClawError::Config(format!("Failed to read API key: {e}")))?;
        if key.trim().is_empty() {
            None
        } else {
            Some(key.trim().to_string())
        }
    } else {
        None
    };

    let answers = InitAnswers {
        anthropic_api_key,
        openai_api_key,
    };

    // Skip writing if no keys provided
    if answers.anthropic_api_key.is_none() && answers.openai_api_key.is_none() {
        prompter.println("No API keys provided. Skipping config file creation.");
        prompter.println(
            "You can set keys via environment variables (ANTHROPIC_API_KEY, OPENAI_API_KEY).",
        );
        return Ok(());
    }

    let toml = generate_config_toml(&answers);
    write_config(config_path, &toml)?;

    prompter.println("");
    prompter.println(&format!("Config written to {}", config_path.display()));
    prompter.println("");
    prompter.println("Try it out: clawzero \"Hello, world!\"");

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::VecDeque;

    struct MockPrompter {
        outputs: Vec<String>,
        passwords: VecDeque<String>,
        confirms: VecDeque<bool>,
    }

    impl MockPrompter {
        fn new(passwords: Vec<&str>, confirms: Vec<bool>) -> Self {
            Self {
                outputs: Vec::new(),
                passwords: passwords.into_iter().map(|s| s.to_string()).collect(),
                confirms: confirms.into_iter().collect(),
            }
        }
    }

    impl InitPrompter for MockPrompter {
        fn println(&mut self, msg: &str) {
            self.outputs.push(msg.to_string());
        }

        fn read_password(&mut self, _prompt: &str) -> io::Result<String> {
            self.passwords
                .pop_front()
                .ok_or_else(|| io::Error::new(io::ErrorKind::UnexpectedEof, "no more passwords"))
        }

        fn confirm(&mut self, _prompt: &str) -> io::Result<bool> {
            self.confirms
                .pop_front()
                .ok_or_else(|| io::Error::new(io::ErrorKind::UnexpectedEof, "no more confirms"))
        }
    }

    #[test]
    fn test_generate_config_anthropic_only() {
        let answers = InitAnswers {
            anthropic_api_key: Some("sk-ant-test123".to_string()),
            openai_api_key: None,
        };
        let toml = generate_config_toml(&answers);
        assert!(toml.contains("[providers.anthropic]"));
        assert!(toml.contains("sk-ant-test123"));
        assert!(!toml.contains("[providers.openai]"));
    }

    #[test]
    fn test_generate_config_both_providers() {
        let answers = InitAnswers {
            anthropic_api_key: Some("sk-ant-test".to_string()),
            openai_api_key: Some("sk-openai-test".to_string()),
        };
        let toml = generate_config_toml(&answers);
        assert!(toml.contains("[providers.anthropic]"));
        assert!(toml.contains("sk-ant-test"));
        assert!(toml.contains("[providers.openai]"));
        assert!(toml.contains("sk-openai-test"));
    }

    #[test]
    fn test_generate_config_no_keys() {
        let answers = InitAnswers {
            anthropic_api_key: None,
            openai_api_key: None,
        };
        let toml = generate_config_toml(&answers);
        assert!(!toml.contains("[providers."));
        assert!(toml.contains("[defaults]"));
    }

    #[test]
    fn test_generated_config_parses_as_valid_toml() {
        let answers = InitAnswers {
            anthropic_api_key: Some("sk-ant-roundtrip".to_string()),
            openai_api_key: Some("sk-openai-roundtrip".to_string()),
        };
        let toml_str = generate_config_toml(&answers);
        let parsed: crate::config::types::AppConfig =
            toml::from_str(&toml_str).expect("Generated TOML should parse as AppConfig");
        assert_eq!(parsed.defaults.model, "anthropic/claude-sonnet-4-20250514");
        assert_eq!(parsed.defaults.max_tokens, 8192);
        let anthropic = parsed
            .providers
            .get("anthropic")
            .expect("anthropic provider");
        assert_eq!(anthropic.api_key.as_deref(), Some("sk-ant-roundtrip"));
        let openai = parsed.providers.get("openai").expect("openai provider");
        assert_eq!(openai.api_key.as_deref(), Some("sk-openai-roundtrip"));
    }

    #[test]
    fn test_write_config_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        write_config(&path, "test content").unwrap();
        assert!(path.exists());
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "test content");
    }

    #[test]
    fn test_write_config_creates_parent_dirs() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("nested").join("deep").join("config.toml");
        write_config(&path, "nested content").unwrap();
        assert!(path.exists());
    }

    #[cfg(unix)]
    #[test]
    fn test_write_config_unix_permissions() {
        use std::os::unix::fs::PermissionsExt;
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        write_config(&path, "secret").unwrap();
        let perms = std::fs::metadata(&path).unwrap().permissions();
        assert_eq!(perms.mode() & 0o777, 0o600);
    }

    #[test]
    fn test_run_init_happy_path() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        // passwords: anthropic key; confirms: yes to OpenAI; passwords: openai key
        let mut prompter = MockPrompter::new(
            vec!["sk-ant-happy", "sk-openai-happy"],
            vec![true], // confirm OpenAI
        );
        run_init(&mut prompter, &path).unwrap();
        assert!(path.exists());
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("sk-ant-happy"));
        assert!(content.contains("sk-openai-happy"));
        assert!(prompter.outputs.iter().any(|o| o.contains("Try it out")));
    }

    #[test]
    fn test_run_init_existing_config_abort() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(&path, "existing").unwrap();
        let mut prompter = MockPrompter::new(
            vec![],
            vec![false], // decline overwrite
        );
        run_init(&mut prompter, &path).unwrap();
        assert_eq!(std::fs::read_to_string(&path).unwrap(), "existing");
    }

    #[test]
    fn test_run_init_existing_config_overwrite() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        std::fs::write(&path, "old content").unwrap();
        let mut prompter = MockPrompter::new(
            vec!["sk-ant-new", "sk-openai-new"],
            vec![true, true], // overwrite + configure OpenAI
        );
        run_init(&mut prompter, &path).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("sk-ant-new"));
        assert!(!content.contains("old content"));
    }

    #[test]
    fn test_run_init_no_keys_skips_write() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("config.toml");
        let mut prompter = MockPrompter::new(
            vec![""],    // empty anthropic key
            vec![false], // decline OpenAI
        );
        run_init(&mut prompter, &path).unwrap();
        assert!(!path.exists());
    }
}
